# Generated by Django 2.2.2 on 2020-01-16 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('award', '0002_awardpost_project_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardpost',
            name='project_link',
            field=models.URLField(max_length=250),
        ),
    ]
